import { test } from 'node:test';
import assert from 'node:assert/strict';
import { looksLikeAadhaar, verhoeff } from './verhoeff.ts';

// Fabricated numbers, generated by computing the check digit, never a real ID.
test('accepts numbers carrying a correct check digit', () => {
  assert.ok(verhoeff('234567890124'));
  assert.ok(verhoeff('999999999999'));
});

test('rejects a single wrong digit', () => {
  assert.ok(!verhoeff('234567890123'));
  assert.ok(!verhoeff('234567890125'));
});

test('rejects a transposition, which a modulus check would miss', () => {
  // The reason Aadhaar uses Verhoeff at all: swapped neighbours are the most
  // common human typing error and mod-10 sums are blind to them.
  assert.ok(verhoeff('234567890124'));
  assert.ok(!verhoeff('234567809124'));
});

test('rejects anything that is not digits', () => {
  assert.ok(!verhoeff(''));
  assert.ok(!verhoeff('2345 6789 0124'));
  assert.ok(!verhoeff('23456789012x'));
});

test('first digit must be 2 through 9', () => {
  assert.ok(looksLikeAadhaar('234567890124'));
  assert.ok(!looksLikeAadhaar('034567890124'));
  assert.ok(!looksLikeAadhaar('134567890124'));
  assert.ok(!looksLikeAadhaar('23456789012'));
});
